CREATE TABLESPACE tbs_01
    DATAFILE 'tbs_01.dat'
    SIZE 50M
    ONLINE;
    
CREATE TEMPORARY TABLESPACE tbs_tem_01
    TEMPFILE 'tbs_tem_01.dbf'
    SIZE 10M
    AUTOEXTEND ON;
    
CREATE USER BED_LINEN
    IDENTIFIED BY lolo4
    DEFAULT TABLESPACE tbs_01
    TEMPORARY TABLESPACE tbs_tem_01
    QUOTA 20M ON tbs_01;
    
CREATE TABLE BED_LINEN.CUSTOMER (
    first_name VARCHAR2(40) NOT NULL PRIMARY KEY,
    last_name VARCHAR(40) NOT NULL,
    phone NUMBER(11),
    adress VARCHAR2(40) NOT NULL
    ); 
    

    
    
