SHOW CON_NAME;



CREATE BIGFILE TABLESPACE alien_tbs_01
    DATAFILE 'alien_tbs_01.dat'
    SIZE 50M 
    AUTOEXTEND ON;
/    



CREATE BIGFILE TEMPORARY TABLESPACE alien_temp_01
    TEMPFILE 'alien_temp_01.dbf'
    SIZE 30M
    AUTOEXTEND ON;
/



CREATE USER ZIREAEL
IDENTIFIED BY wither112
DEFAULT TABLESPACE alien_tbs_01
QUOTA 100M ON alien_tbs_01
TEMPORARY TABLESPACE alien_temp_01
QUOTA 5M ON system;
/



SAVEPOINT created_user;
/



COMMIT;
/



CREATE TABLE ZIREAEL.DEPARTMENT (
    DEPT_ID NUMBER,
    DEPARTMENT VARCHAR2(25),
    CONSTRAINT dept_pk PRIMARY KEY(dept_id)
);
/ 



CREATE TABLE ZIREAEL.PROVIDERS (
    ID NUMBER,
    NAME VARCHAR2(90),
    COMPANY VARCHAR2(60),
    PHONE_NUMBER NUMBER(11),
    E_MAIL VARCHAR2(100),
    CONSTRAINT prov_fk 
        FOREIGN KEY(id)
        REFERENCES ZIREAEL.DEPARTMENT(dept_id)
);
/



COMMIT;
/


CREATE TABLE ZIREAEL.LIBRARY (
    NUMBER_STORE NUMBER,
    GENRE VARCHAR2(43),
    AUTHOR VARCHAR2(50),
    NAME_BOOK VARCHAR2(100),
    NUMBER_BOOK NUMBER CHECK(number_book <= 10000),
    CONSTRAINT library_fk
        FOREIGN KEY(number_store)
        REFERENCES ZIREAEL.DEPARTMENT(dept_id)
);
/



CREATE TABLE ZIREAEL.PURCHASE (
    INVOICE NUMBER,
    DATE_ORDER TIMESTAMP(8),
    AUTHOR VARCHAR2(50),
    NAME_BOOK VARCHAR2(100),
    PRICE NUMBER,
    NUMBER_GOOD NUMBER,
    CONSTRAINT pur_fk
        FOREIGN KEY(invoice)
        REFERENCES ZIREAEL.DEPARTMENT(dept_id)
);
/



CREATE TABLE ZIREAEL.EMPLOYEES (
    EMPLOYEE_ID NUMBER,
    POST VARCHAR2(30),
    DEPT_ID NUMBER,
    NAME VARCHAR2(90),
    PHONE_NUMBER NUMBER(11),
    CONSTRAINT emp_pk PRIMARY KEY(employee_id),
    CONSTRAINT emp_dept_fk
        FOREIGN KEY(dept_id)
        REFERENCES ZIREAEL.DEPARTMENT(dept_id)
);
/



CREATE TABLE ZIREAEL.SALES (
    SELLER_ID NUMBER,
    SELLER_NAME VARCHAR2(90),
    NUMBER_CHECK NUMBER,
    DATE_ORDER TIMESTAMP(8),
    NAME_BOOK VARCHAR2(100),
    PRICE NUMBER,
    NUMBER_GOOD NUMBER,
    CONSTRAINT sal_emp_fk
        FOREIGN KEY(seller_id)
        REFERENCES ZIREAEL.EMPLOYEES(employee_id),
    CONSTRAINT sal_check_dept_fk
        FOREIGN KEY(number_check)
        REFERENCES ZIREAEL.DEPARTMENT(dept_id)
);
/



COMMIT;



SAVEPOINT all_tables_created;